on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    container: 'rocker/r-base:latest'

    steps:
      - uses: actions/checkout@v2
      - name: run something in R
        run: Rscript -e 'date()' -e 'format(Sys.time(), "%a %b %d %X %Y")'
