on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    container: 'rocker/tidyverse:latest'

    steps:
      - uses: actions/checkout@v2
      - name: install icesTAF
        run: Rscript -e 'install.packages("icesTAF")'
      - name: install icesSAG
        run: Rscript -e 'remotes::install_github("ices-tools-prod/icesSAG@development")'
      - name: getwd 
        run: Rscript -e 'getwd()'
      - name: print directory structure
        run: Rscript -e 'dir(recursive = TRUE)'   
      - name: run bootstrap
        run: Rscript -e 'icesTAF::taf.bootstrap(software=FALSE)'
      - name: run sourceAll
        run: Rscript -e 'icesTAF::sourceAll()'
      - name: print directory structure again
        run: Rscript -e 'dir(recursive = TRUE)'
      - name: Commit files
        run: |
          git config --local user.email "ices@github.com"
          git config --local user.name "ices-github-bot"
          git add --all -f
          git commit -m "Add worflow results"
      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
