on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    container: 'rocker/tidyverse:latest'

    steps:
      - uses: actions/checkout@v2
      - name: install icesTAF
        run: Rscript -e 'install.packages(\"icesTAF\")'
      - name: run bootstrap
        run: Rscript -e 'icesTAF::taf.boostrap()'
