on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    container: 'rocker/tidyverse:latest'

    steps:
      - uses: actions/checkout@v2
      - name: install icesTAF
        run: Rscript -e 'install.packages("icesTAF")'
      - name: install icesSAG
        run: Rscript -e 'remotes::install_github("ices-tools-prod/icesSAG@dc9098f")'
      - name: run bootstrap
        run: Rscript -e 'icesTAF::taf.bootstrap(software=FALSE)'
      - name: run sourceAll
        run: Rscript -e 'icesTAF::sourceAll()'
